### ISSUE TITLE
How to get only the updates / changed files ?

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOpsWeb#1]
so i dont accidentally overwrite stuff like the database.yml ?

**Comment by Drutol** [comment]
Clone the repo using git and then just use "git pull"

**Comment by Hysteriana** [comment]
clone as in "clone in desktop" or fork ?

**Comment by Drutol** [comment]
git clone <git url>

**Comment by Drutol** [comment]
git clone "git url"

**Comment by Hysteriana** [comment]
ok now you have lost me...

**Comment by Hysteriana** [comment]
little step by step pls ? ^^

**Comment by Drutol** [comment]
1. open terminal/shell/console
2. git clone https://github.com/Mordonus/RaidOpsWeb.git

**Comment by Drutol** [comment]
then to update:
git pull

**Comment by Drutol** [comment]
And to aviod overwrittig certain files set up .gitignore ^^ https://help.github.com/articles/ignoring-files/

**Comment by Hysteriana** [comment]
got it
