### ISSUE TITLE
data download doesnt work

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOpsWeb#3]
item links are working now.
but still cant download data

**Comment by Drutol** [comment]
Because you need "environmental variables" containing various passwords etc.

**Comment by Hysteriana** [comment]
uuhmmmm...

/config/environment.rb ?

**Comment by Drutol** [comment]
PM on curse ^^

**Comment by Hysteriana** [comment]
curse pm has no infos about the environmental variables ^^

**Comment by Drutol** [comment]
But it will , in the evening :p
